_wandb:
    value:
        cli_version: 0.21.0
        e:
            9d32z191atlslf5f55np1hufn6e2aytj:
                codePath: run_pipeline.py
                codePathLocal: run_pipeline.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1006450962432"
                        used: "919409135616"
                email: olr7742@nyu.edu
                executable: /home/lambda1/Documents/thor-grasp/myenv/bin/python
                git:
                    commit: 7e5275bf0db0266ea9b8a8c3ba0156bdc3450db5
                    remote: https://github.com/omarrayyann/thor-grasp.git
                gpu: NVIDIA GeForce RTX 3070 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070 Ti Laptop GPU
                      uuid: GPU-ebdf6a4c-4cba-13d4-6fbb-d552e45ad3ca
                host: lambda1-TensorBook-2022
                memory:
                    total: "33321197568"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/lambda1/Documents/thor-grasp/run_pipeline.py
                python: CPython 3.10.12
                root: /home/lambda1/Documents/thor-grasp
                startedAt: "2025-07-08T23:58:01.854367Z"
                writerId: 9d32z191atlslf5f55np1hufn6e2aytj
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
approach_distance:
    value: 0.1
approach_steps:
    value: 1000
max_grasps_to_visualize:
    value: 2000
max_successful_grasps:
    value: 1000
total_objects:
    value: 1
